language: java

services:
  - docker

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      name: 'Building docker image without tests'
      script:
        - make build/docker
    - stage: deploy
#      if: tag IS present
      name: 'Deploy application on heroku'
      script:
        - make deploy